name: unit-test
description: Base package unit test action
inputs:
  package:
    description: Package name to run unit tests on
    required: true
runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
      shell: bash

    - name: Run unit tests
      run: pnpm --filter ${{ inputs.package }} run test
      shell: bash